services:
  rasa:
    image: rasa/rasa:3.5.11
    container_name: rasa
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command: run --enable-api --cors "*"
    depends_on:
      - action_server

  action_server:
    build:
      context: ./actions
      dockerfile: Dockerfile
    container_name: action_server
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app
    command: ["python", "-m", "rasa_sdk", "--actions", "actions"]

